FROM node:12-alpine

RUN apk --update --no-cache add zip

ENV INSTALL_PATH /var/task

WORKDIR $INSTALL_PATH

COPY package.json yarn.lock ./
RUN yarn install --no-cache --frozen-lockfile --ignore-optional && \
    yarn autoclean --force && \
    yarn global add serverless

COPY . .

CMD ["serverless", "deploy"]
