FROM node:12-alpine

WORKDIR /opt

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile --ignore-optional \
  && yarn global add serverless

WORKDIR /var/task

COPY . .

CMD ["serverless", "deploy", "--stage=$STAGE"]
