FROM node:12-alpine

WORKDIR /opt

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile --ignore-optional \
  && yarn global add serverless

ENV PATH=/opt/node_modules/.bin:${PATH}

WORKDIR /var/task

COPY . .

# must run in shell for env var interpolation
CMD ["sh", "-c", "serverless deploy --stage=$STAGE --region=$AWS_REGION"]
