# Thanks to https://hub.docker.com/r/amazon/aws-lambda-nodejs
# Dockerfiles documented in https://github.com/aws/aws-lambda-base-images
FROM amazon/aws-lambda-nodejs:14

COPY . ${LAMBDA_TASK_ROOT}

CMD [ "handler.syntheticTest" ]
