FROM quay.io/nyulibraries/web-lambdas-terraform:v0.15.0-0

# Get the latest yq v4 from the edge mirror per https://mikefarah.gitbook.io/yq/#alpine-linux
RUN echo "https://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories

RUN apk update && \
    apk upgrade && \
    apk add --no-cache gettext yq~=4

COPY .tf_env_vars config.yml scripts/ ./

RUN chmod a+x ./*.sh
